name: CI
on: push
jobs:

  build:
    strategy:
      matrix:
        go-version:
          - ~1.15
          - ~1.16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-verison }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -cover ./...
